name: 'the-mintable/aws-login'
description: 'GitHub Action to login to AWS'
author: '@the-mintable'

branding:
  icon: 'box'
  color: 'blue'

# ======================================================================================================================
inputs:

  aws-account:
    required: true

  aws-region:
    required: true

  codeartifact:
    description: 'The CodeArtifact domain name, if required.'
    required: false
    default: ''

  docker:
    description: 'Whether or not Docker will be used.'
    required: false
    default: true

  login:
    required: false
    default: true

# ======================================================================================================================
runs:
  using: 'composite'

  steps:

    - name: Prepare environment variables
      shell: bash
      run: |
        echo "AWS_ROLE=github-${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "DOCKER_DOMAIN=${{inputs.aws-account}}.dkr.ecr.${{inputs.aws-region}}.amazonaws.com" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ inputs.login != 'false' }}
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ env.AWS_ROLE }}

    - name: Login to Amazon CodeArtifact
      if: ${{ inputs.codeartifact != '' }}
      shell: bash
      run: |
        cmd="aws codeartifact get-authorization-token"
        tmp="$($cmd --domain ${{ inputs.codeartifact }} --domain-owner ${{ inputs.aws-account }} --region ${{ inputs.aws-region }} --query authorizationToken --output text)"
        if [ -z "$tmp" ]; then
          echo "::error::$cmd failed."
          exit 1
        else
          echo "::add-mask::$tmp"
          echo "CODEARTIFACT_AUTH_TOKEN=$tmp" >> $GITHUB_ENV
          tmp=
        fi

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      if: ${{ inputs.docker != 'false' }}

    - name: Cache docker layers
      uses: satackey/action-docker-layer-caching@v0.0.11
      if: ${{ inputs.docker != 'false' }}
      continue-on-error: true
      with:
        key: docker-layer-cache-{hash}
        restore-keys: |
          docker-layer-cache-
          layer-docker-layer-cache-
