name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./
        with:
          aws-account: 123
          aws-region: xyx
          codeartifact:
          docker: false
          login: false

      - name: Env
        run: env|sort
